### ISSUE TITLE
inotifywait does not account all files that haproxy read

### ISSUE THREAD

**Issue by asquelt** [million12/docker-haproxy#10]
ie. errorfiles or certificates that are being specified in `haproxy.cfg`.
those are being read only once - on haproxy start.

two possible solutions for this:
1. monitor `/etc/haproxy` (or whichever dir where `haproxy.cfg` resides) - this assumes that most people place entire haproxy configuration under etc, ie. `inotifywait -r -q -e create,delete,modify,attrib $(dirname $HAPROXY_CONFIG) /etc/hosts`
2. parse `haproxy.cfg` and add files and directories (`crt` directive might specify directory to watch) - unfortunately haproxy's own `src/cfgparse.c` doesn't have an abstract function for reading files, so this would require to reparse in bash.

**Comment by pozgo** [comment]
Good thinking... 

Please feel free to send us Pull Request.

**Comment by pozgo** [comment]
Apparently, inotifywait doesn't want to work with directories. I have added a new variable in which user can specify extra files that should be monitored. Not best solution but only one I could work in short time :)

**Comment by pozgo** [comment]
Fixed since 1.7.9 release
