### ISSUE TITLE
Configuring logging

### ISSUE THREAD

**Issue by mkhutornenko** [million12/docker-haproxy#12]
Big thanks for putting it all together! This has been very helpful in enabling our e2e gRPC-based channel.

The only issue that we found lacking in this example is the explicit support for configurable logging/tracing. This could be invaluable in troubleshooting edge cases like SSL termination or backend SSL. Has anyone solved this before and willing to share their experience? Are you using rsyslog or a some kind of sidecar container solution (e.g.: https://github.com/dockerfile/haproxy/issues/3)?

**Comment by mkhutornenko** [comment]
If anyone interested, I ended up directly enabling rsyslog in the image: https://github.com/mkhutornenko/docker-haproxy

This way all logging is directly controlled from the haproxy.config.

**Comment by pozgo** [comment]
Closing due to the HAProxy config related issue, not docker image.
