### ISSUE TITLE
config : 'http-request' rules ignored for backend 'nodes-http2' as they require HTTP mode.

### ISSUE THREAD

**Issue by Cactusbone** [million12/docker-haproxy#13]
In the default configuration, there is 
```
backend nodes-http2
    mode tcp
    http-request add-header X-Forwarded-Proto https
    server node1 web.server:81 check send-proxy
```
Using a similar conf I get `[WARNING] 122/144630 (11) : config : 'http-request' rules ignored for backend 'nodes-http2' as they require HTTP mode.`
So i was wondering if it should be working or if there's something in the config that somehow make this work

**Comment by pozgo** [comment]
Closing due to HAProxy config related issue not this docker image. 

If needed please reopen.
