### ISSUE TITLE
Pre and Post reload hooks

### ISSUE THREAD

**Issue by swapnilsm** [million12/docker-haproxy#16]
@ryzy @pozgo I think we should allow some pre and post reload hooks to run some commands inside the container. 
This will make supporting few use cases such as following possible. 
_Seamless server reload section of - https://www.haproxy.com/blog/whats-new-in-haproxy-1-6/_

One way of implementing this is by taking in few extra environment variables and executing those accordingly.

I can take this up if you like to.

**Comment by pozgo** [comment]
Hi @swapnilsm. It looks good to me. I cannot see PR though ;) Send it to us and I'll merge it. Thanks a lot!!!

**Comment by swapnilsm** [comment]
Done

**Comment by pozgo** [comment]
Merged PR

Thanks a lot!
