### ISSUE TITLE
HAProxy exits immediately - inotifywait prevents container exiting

### ISSUE THREAD

**Issue by jamesroyer** [million12/docker-haproxy#17]
For some reason haproxy exits immediately but the return code is 0. When I attach to the container and run "ps -ef" there is no haproxy process. The container eventually exits when the file changes and it can't find the PID file.

One other issue is that you allow the ports to be overridden using HAPROXY_PORTS but the Dockerfile exposes 80 and 443. I don't think it is possible to extend your container and un-expose those ports (see issue [3465](https://github.com/moby/moby/issues/3465)) and expose different ports.

**Comment by pozgo** [comment]
@jamesroyer SHould we close this as it's no longer an issue?

**Comment by pozgo** [comment]
I consider it user input error, not an image issue. Closing
