### ISSUE TITLE
Support /etc/hosts linked containers

### ISSUE THREAD

**Issue by jimbeveridge** [million12/docker-haproxy#3]
Docker automatically updates the file /etc/hosts whenever a container changes if you are using linked containers. If you could modify your inotify command to monitor /etc/hosts, it would make haproxy updates happen automatically with linked containers.

More details at:
https://docs.docker.com/userguide/dockerlinks/#updating-the-etchosts-file

Thanks!

**Comment by ryzy** [comment]
You're right, sounds like a great idea, we'll do (or feel free sending PR request).

**Comment by jimbeveridge** [comment]
Thanks. I tried testing the change yesterday, but updating /etc/hosts is documented as broken in Docker 1.4.1, which is the version I'm running. The feature is supposed to be fixed for 1.5. So I will let you do the change when you feel it's appropriate.
