### ISSUE TITLE
Use zero-downtime restart method described by yelp

### ISSUE THREAD

**Issue by sheerun** [million12/docker-haproxy#8]
http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html

What do you think?

**Comment by pozgo** [comment]
I think it's brilliant idea. When I fins dome time i'll do some tests and implement it into our image. Unless someone is willing to send PR :) 

@sheerun thanks for this!

**Comment by swapnilsm** [comment]
I can take this up. To start with we can implement Willy's [solution](http://marc.info/?l=haproxy&m=133262017329084&w=2).

**Comment by pozgo** [comment]
Fixed with PR [#14](https://github.com/million12/docker-haproxy/pull/14)
